/** Search, answer-engine, and generative crawlers welcome on public pages. */
export const AI_AND_SEARCH_AGENTS = [
  "Googlebot",
  "Googlebot-Image",
  "Google-Extended",
  "Google-CloudVertexBot",
  "GoogleOther",
  "Bingbot",
  "BingPreview",
  "DuckDuckBot",
  "DuckAssistBot",
  "Slurp",
  "YandexBot",
  "Applebot",
  "Applebot-Extended",
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "ClaudeBot",
  "Claude-User",
  "Claude-SearchBot",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "Amazonbot",
  "CCBot",
  "Bytespider",
  "meta-externalagent",
  "FacebookBot",
  "cohere-ai",
  "YouBot",
  "Diffbot",
  "Timpibot",
  "CloudflareBrowserRenderingCrawler",
] as const;
